USE [master]
GO
/****** Object:  Database [ExamenFinalDB]    Script Date: 20/12/2024 10:15:27 ******/
CREATE DATABASE [ExamenFinalDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExamenFinalDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ExamenFinalDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ExamenFinalDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ExamenFinalDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ExamenFinalDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExamenFinalDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ExamenFinalDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ExamenFinalDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ExamenFinalDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ExamenFinalDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ExamenFinalDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ExamenFinalDB] SET  MULTI_USER 
GO
ALTER DATABASE [ExamenFinalDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ExamenFinalDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ExamenFinalDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ExamenFinalDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ExamenFinalDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ExamenFinalDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ExamenFinalDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [ExamenFinalDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ExamenFinalDB]
GO
/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 20/12/2024 10:15:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Assignments]    Script Date: 20/12/2024 10:15:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Assignments](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeId] [int] NOT NULL,
	[ProjectId] [int] NOT NULL,
	[FechaAsignacion] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.Assignments] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 20/12/2024 10:15:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NumeroCarnet] [nvarchar](max) NULL,
	[Nombre] [nvarchar](max) NULL,
	[FechaNacimiento] [datetime] NOT NULL,
	[Categoria] [nvarchar](max) NULL,
	[Salario] [decimal](18, 2) NOT NULL,
	[Direccion] [nvarchar](max) NULL,
	[Telefono] [nvarchar](max) NULL,
	[Correo] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.Employees] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Projects]    Script Date: 20/12/2024 10:15:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Projects](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [nvarchar](max) NULL,
	[Nombre] [nvarchar](max) NULL,
	[FechaInicio] [datetime] NOT NULL,
	[FechaFin] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.Projects] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_EmployeeId]    Script Date: 20/12/2024 10:15:28 ******/
CREATE NONCLUSTERED INDEX [IX_EmployeeId] ON [dbo].[Assignments]
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_ProjectId]    Script Date: 20/12/2024 10:15:28 ******/
CREATE NONCLUSTERED INDEX [IX_ProjectId] ON [dbo].[Assignments]
(
	[ProjectId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Assignments]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Assignments_dbo.Employees_EmployeeId] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[Employees] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Assignments] CHECK CONSTRAINT [FK_dbo.Assignments_dbo.Employees_EmployeeId]
GO
ALTER TABLE [dbo].[Assignments]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Assignments_dbo.Projects_ProjectId] FOREIGN KEY([ProjectId])
REFERENCES [dbo].[Projects] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Assignments] CHECK CONSTRAINT [FK_dbo.Assignments_dbo.Projects_ProjectId]
GO
USE [master]
GO
ALTER DATABASE [ExamenFinalDB] SET  READ_WRITE 
GO
